services:
  vowerp-backend:
    image: ghcr.io/tarunsadhukhan/sjmebe:latest
    build:
      context: .
    container_name: vowerp-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - TZ=Asia/Kolkata
    networks:
      - vowerp

  vowerp-scheduler:
    image: ghcr.io/tarunsadhukhan/sjmebe:latest
    container_name: vowerp-scheduler
    restart: unless-stopped
    command: uvicorn src.scheduler_main:app --host 0.0.0.0 --port 48480
    ports:
      - "48480:48480"
    env_file: .env
    environment:
      - TZ=Asia/Kolkata
    networks:
      - vowerp

networks:
  vowerp:
    external: true
